### ISSUE TITLE
image-url() returning backslach path on Windows

### ISSUE THREAD

**Issue by stephenasamoah** [Jman/postcss-compass#1]
I'm running on Windows 10. Unfortunately the image-url() function returns backslashed paths when I use it. font-url() doesn't work at all. I installed the compass-mixins via bower and imported it into my fonts partial.

Here's what I mean.
**1. image-url() function output**:

> background: #2b333c url('..\..\assets\images\lightbulbs.jpg') 50% 50% no-repeat;

instead of:
background: #2b333c url('../../assets/images/lightbulbs.jpg') 50% 50% no-repeat;

**2. font-url() fucntion output**:
 

> @font-face {
>   font-family: "gulp";
>   src: font_files("gulp.eot", "gulp.svg", "gulp.ttf", "gulp.woff");
> }

instead of:
@font-face {
  font-family: "gulp";
  src: url('../../assets/fonts/gulp.eot') format('embedded-opentype'), url('../../assets/fonts/gulp.svg') format('svg'), url('../../assets/fonts/gulp.ttf') format('truetype'), url('../../assets/fonts/gulp.woff') format('woff');
}

**Comment by Jman** [comment]
Sorry for long answer
Check a new version for fix win32 paths.
The issue with your  font-url  is in typo. You need to use `font-files` instead of `font_files`.
